DROP TABLE IF EXISTS users;

CREATE TABLE
  users (
    user_id SERIAL NOT NULL PRIMARY KEY,
    username VARCHAR(30) NOT NULL UNIQUE,
    password VARCHAR(8) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    token TEXT
  );

DROP TABLE IF EXISTS books;

CREATE TABLE
  books (
    book_id SERIAL NOT NULL PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    author VARCHAR(30) NOT NULL,
    genre VARCHAR(15) NOT NULL,
    publication_date DATE NOT NULL,
    isbn VARCHAR(10) NOT NULL UNIQUE
  );